# Generated by Django 4.2.6 on 2023-11-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perm',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
